import {
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  BadgePercent,
  BarChart3,
  Bell,
  Box,
  Briefcase,
  Building2,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronUp,
  CircleDollarSign,
  CircleSlash,
  Clock,
  Columns3,
  Copy,
  CreditCard,
  Download,
  ExternalLink,
  Eye,
  File,
  FileCheck2,
  FilePlus2,
  FileText,
  Filter,
  FolderOpen,
  Grid2x2,
  Home,
  Info,
  LayoutGrid,
  Lightbulb,
  Link2,
  Loader2,
  Lock,
  Mail,
  MapPin,
  Menu,
  Minus,
  MoreVertical,
  Package,
  PackageCheck,
  PackageOpen,
  Pencil,
  Phone,
  Play,
  Plus,
  Printer,
  ReceiptText,
  RefreshCw,
  RotateCcw,
  Rows3,
  Ruler,
  Save,
  ScanBarcode,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Star,
  Tag,
  Trash2,
  TrendingUp,
  Truck,
  Upload,
  User,
  Users,
  Warehouse,
  X,
  XCircle,
  type LucideProps,
} from "lucide-react";

/**
 * Curated icon set. Keeping a named map (rather than importing lucide by
 * string at call sites) means schemas reference icons by a stable domain name
 * and the bundle only ships what we actually use.
 */
export const ICONS = {
  // Navigation / modules
  dashboard: Home,
  product: Package,
  category: FolderOpen,
  partner: Users,
  warehouse: Warehouse,
  salesRep: Briefcase,
  priceList: Tag,
  pricing: CircleDollarSign,
  uom: Ruler,
  workspace: LayoutGrid,
  purchaseRequest: FilePlus2,
  purchaseOrder: FileCheck2,
  goodsReceipt: PackageCheck,
  qc: ShieldCheck,
  putAway: Truck,
  outbound: Truck,
  salesRequest: FileText,
  salesOrder: FileText,
  picking: PackageOpen,
  packing: Box,
  delivery: Truck,
  invoice: ReceiptText,
  return: RotateCcw,
  creditNote: CreditCard,
  promotion: BadgePercent,
  reports: BarChart3,
  settings: Settings,
  company: Building2,

  // Domain
  box: Package,
  layers: Box,
  tag: Tag,
  truck: Truck,
  cart: ShoppingCart,
  shield: Shield,
  file: File,
  clock: Clock,
  lock: Lock,
  alert: AlertTriangle,
  barcode: ScanBarcode,
  user: User,
  users: Users,
  mapPin: MapPin,
  phone: Phone,
  mail: Mail,
  calendar: Calendar,
  bulb: Lightbulb,
  trend: TrendingUp,
  grid: Grid2x2,

  // UI
  search: Search,
  bell: Bell,
  menu: Menu,
  close: X,
  plus: Plus,
  minus: Minus,
  check: Check,
  checkCircle: CheckCircle2,
  xCircle: XCircle,
  circleSlash: CircleSlash,
  info: Info,
  download: Download,
  upload: Upload,
  filter: Filter,
  columns: Columns3,
  rows: Rows3,
  refresh: RefreshCw,
  more: MoreVertical,
  edit: Pencil,
  copy: Copy,
  trash: Trash2,
  star: Star,
  printer: Printer,
  eye: Eye,
  link: Link2,
  external: ExternalLink,
  save: Save,
  send: Send,
  play: Play,
  sliders: SlidersHorizontal,
  spinner: Loader2,
  sort: ArrowUpDown,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  collapse: ChevronsLeft,
} as const;

export type IconName = keyof typeof ICONS;

interface IconProps extends Omit<LucideProps, "ref"> {
  name: IconName;
  size?: number;
}

/** All icons render as outline strokes at 1.75 by default — never filled. */
export function Icon({ name, size = 16, strokeWidth = 1.75, ...rest }: IconProps) {
  const Cmp = ICONS[name];
  return <Cmp size={size} strokeWidth={strokeWidth} {...rest} />;
}
